runtime: custom
env: flex

env_variables:
  SECRET_KEY: "jesherjoshua"
  DATABASE_URL: "mysql+pymysql://root:jj123@34.67.126.30/ctfdtest"
  REDIS_URL: "redis://10.31.225.5:6379"
  REVERSE_PROXY: "2,0,0,0,0"
  # MAILFROM_ADDR: "noreply@downunderctf.com"
  # MAIL_SERVER: "email-smtp.ap-southeast-2.amazonaws.com"
  # MAIL_PORT: "587"
  # MAIL_TLS: "True"
  # MAIL_USEAUTH: "True"
  # MAIL_USERNAME: "[redacted]"
  # MAIL_PASSWORD: "[redacted]"
  UPLOAD_PROVIDER: "s3"
  AWS_ACCESS_KEY_ID: "GOOGYNOD57XM2TQFH3ANFRKJ"
  AWS_SECRET_ACCESS_KEY: "VbWYFgx+MABXbb4Z6aCnVQ/YE7vIBa492Q67K4yn"
  AWS_S3_BUCKET: "ctfdtestbucket"
  AWS_S3_ENDPOINT_URL: "https://storage.googleapis.com"
  WORKERS: 2

network:
  name: default

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

automatic_scaling:
  cpu_utilization: 
    target_utilization: 0.7
